version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  # the build job
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      # pull node_modules from cache
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      # cache the node_modules
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
      # build the project
      - run:
          name: Building
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
                  npm run build-dev
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                  npm run build-prod
            else
                  npm run build-dev
            fi
      # cache dist folder for deploy job
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
  # the deploy job
  deploy_dev:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - aws-s3/sync:
          from: 'dist'
          to: $BUCKET_NAME_DEV
          arguments: --delete
      - aws-cli/setup:
              profile-name: default
              aws-region: $AWS_REGION
      # - run: 
      #     name: Invalidate cache
      #     command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_DEV \
      #     --paths /*
  deploy_master:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - aws-s3/sync:
          from: 'dist'
          to: $BUCKET_NAME_PROD
          arguments: --delete
      - aws-cli/setup:
          profile-name: default
          aws-region: $AWS_REGION
      # - run: 
      #     name: Invalidate cache
      #     command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_PROD \
      #     --paths /*
workflows:
  # version: 2
  # the build and deploy workflow dev
  build_and_deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            # require build to pass before we can deploy
            - build
          filters:
            branches:
                only:
                  # only run on dev and master branches
                  - dev
      - deploy_master:
          requires:
            # require build to pass before we can deploy
            - build
          filters:
            branches:
                only:
                  # only run on dev and master branches
                  - master
  